### ISSUE TITLE
phone:INTERNATIONAL rule stopped working

### ISSUE THREAD

**Issue by julienarcin** [Propaganistas/Laravel-Phone#250]
After upgrading to the last version, the validation rule stopped working:

`'phone' => ['required', 'phone:INTERNATIONAL'],`

I'm running a test and trying to create a phone with number +12345678901234, it should return a validation error.

But I get an exception: 

```
TypeError: libphonenumber\PhoneNumberUtil::isValidNumberForRegion(): Argument #2 ($regionCode) must be of type string, null given, called in /Users/julienarcin/Code/template-application/vendor/propaganistas/laravel-phone/src/PhoneNumber.php on line 170 and defined in /Users/julienarcin/Code/template-application/vendor/giggsey/libphonenumber-for-php-lite/src/PhoneNumberUtil.php:2958
Stack trace:
#0 /Users/julienarcin/Code/template-application/vendor/propaganistas/laravel-phone/src/PhoneNumber.php(170): libphonenumber\PhoneNumberUtil->isValidNumberForRegion(Object(libphonenumber\PhoneNumber), NULL)
#1 /Users/julienarcin/Code/template-application/vendor/propaganistas/laravel-phone/src/Rules/Phone.php(64): Propaganistas\LaravelPhone\PhoneNumber->isValid()
#2 /Users/julienarcin/Code/template-application/vendor/propaganistas/laravel-phone/src/PhoneServiceProvider.php(34): Propaganistas\LaravelPhone\Rules\Phone->passes('phone', '+12345678901234...')
...
```

**Comment by allmanaj** [comment]
I can confirm that I'm having this same problem!

**Comment by Propaganistas** [comment]
Thanks for reporting; it's fixed now.
